Create email invite confirmation screen
gt-scheduler/website pull request #215
Opened 2023-03-31 06:25 UTC by nathangong

### Summary

Resolves #205 

Creates a confirmation screen for email invite, access through /confirm-invite

### Checklist

#### UI Requirements
~~- [ ] Information about the invitation (i.e., the author of the schedule, its name, and the account that is given access to this schedule) is displayed.~~ -- Figma doesn't specify any of this information (?)

#### Functional Requirements
- [x] The screen automatically redirects after 30s.
- [x] Works for preview sites.

### How to Test
Run it locally and navigate to http://localhost:3000/confirm-invite

2023-04-07 22:11 UTC, samarth52 requested changes
Nice work on this screen! Apart from the in-line comments, please address the following changes as well:
- Integrate `InviteBackLink` and `EmailInviteConfirmation` into one component corresponding to the `/invite/:id` route. This will be used to integrate the Firebase function call that adds the friend
- Implement a state that will be used to modify the contents displayed on the confirmation screen. There are three possible states: Loading, Success, Error (does not need to be this exactly)
- When the user lands on this route, a loading message or symbol should be displayed until `handleInvite` is completed. Do not redirect or display the button that redirects.
- If `handleInvite` is successful, display what is currently shown in `EmailInviteConfirmation` and redirect in 5s
- If `handleInvite` fails, display what is currently shown in `EmailInviteConfirmation` but replace `Congratulations on Adding a New Schedule to your View!` with some apt error message. Redirect in 10s

2023-04-07 22:28 UTC, samarth52 requested changes

2023-04-07 22:28 UTC, samarth52 commented on src/components/EmailInviteConfirmation/stylesheet.scss
> +  @media (max-width: 1000px) {
The page is responsive to the width but not the height. The button appears below the BoG text and logo:

<img src="https://user-images.githubusercontent.com/57265280/230686266-d850f99c-a443-4183-a9aa-a5a465c4a597.jpg" width=200 height=450 />

2023-04-08 04:00 UTC, samarth52 commented on src/components/EmailInviteConfirmation/stylesheet.scss
> +  padding-bottom: 38px;
This applies to line 13

2023-04-10 15:11 UTC, samarth52 requested changes
Great work integrating my comments! There are just a few minor changes to look into. I would also recommend testing it locally using the Firebase emulator with the changes from Yatharth's Firebase functions PR: https://github.com/gt-scheduler/firebase-conf/pull/3

2023-04-11 04:20 UTC, nathangong commented on src/components/InviteBackLink/stylesheet.scss
> +  padding-top: 160px;
get a smaller monitor bruh

2023-04-11 06:54 UTC, samarth52 approved these changes

2023-04-11 06:54 UTC, samarth52 commented
Lgtm 👍

2023-10-19 17:46 UTC, merged