[feature, frontend] Feature/overlapping blocks
gt-scheduler/website pull request #30
Opened 2021-03-29 18:45 UTC by JustinH11235

#### This pull request adds functionality to allow overlapping time blocks to be visually separated from each other (similarly to courseoff).

#### Reason for Feature
Personally, when I make my schedule I tend to pin every section time possible onto my calendar so that I can visually see my options, then I slowly whittle down my selections until I get only one section per course. When switching to gt-scheduler this semester from courseoff, I noticed this approach is difficult when times partially overlap and impossible when they fully overlap.

#### Changes Implemented
1. Within every day, whenever courses time blocks overlap, I modify their 'width' and 'left' CSS properties to make each of these blocks less wide and horizontally separated.
2. Unlike courseoff, I do this in a way so that you can have a grouping of overlapping blocks at the top of the day, each with a width of say 1/3, and have a disjoint grouping of overlapping blocks at the bottom of the day, each with a width of say 1/2.
3. JustinH11235@7fab9359b75a790bceeae17019d3db492b9e0d39 sorts the pinned/overlayCrns from shortest to tallest as a heuristic that attempts to fit the blocks together in a way that minimizes the number of blocks in a row (not necessary but will show before/after pictures below).
#### Note: If users are only selecting classes that do not overlap (i.e. they should each fill the full row), the blocks will look exactly the same with this PR as without this PR. These changes only visually affect time blocks that would normally overlap each other.

## Before PR
![schedulerold1](https://user-images.githubusercontent.com/61996677/112883280-136adb00-909c-11eb-9eda-5ea93bccd1f7.png)

## After PR (without Heuristic) (same courses as before)
Circled in red are cases where we fit the blocks together inefficiently, causing each block's width to be smaller.
![schedulernew3](https://user-images.githubusercontent.com/61996677/112883690-9f7d0280-909c-11eb-8da9-647a25109239.png)

## After PR (with Heuristic)
![schedulernew1](https://user-images.githubusercontent.com/61996677/112881716-051bbf80-909a-11eb-8b86-d4264425993d.png)

I believe this is a necessary feature for many users, but if you have any critiques, additions, changes, etc. please let me know! Also, I am new to open-source contributing so please let me know if I'm doing anything wrong and I'll try to fix it. Hope this is helpful!

2021-03-29 22:14 UTC, jazevedo620 commented
First of all, thanks so much for submitting this pull request 🎉. I really appreciate how detailed the PR is and the extra effort you went through to make it visually appealing.

I will go ahead and take a look at the changes now and get back back to you momentarily.

2021-03-29 22:40 UTC, jazevedo620 requested changes
The code all looks good, though some of it is a little unclear on first read. Some brief comments (on the order of 2-5 lines) would be really helpful to document the approach that the algorithm uses and what exactly it outputs.

2021-03-29 22:40 UTC, jazevedo620 commented on src/components/Calendar/index.js
> +          const updatePrevious = (arr, seen, curCrn, curPeriod) => {
Can you add some comments explaining the purpose of this function?

2021-03-29 22:40 UTC, jazevedo620 commented on src/components/Calendar/index.js
> +  const dayMap = DAYS.reduce((acc, day) => {
It would be useful to include a comment about what exactly this data structure contains

2021-03-29 22:40 UTC, jazevedo620 commented on src/components/Calendar/index.js
> +  crns.forEach((crn) => {
Can you add some comments explaining the overview of the algorithm used here? It seems to be both iterative and recursive and use a visited set, but the exact mechanism is unclear.

2021-03-30 03:17 UTC, JustinH11235 commented
Hopefully the code is clearer after the last commit. While I was cleaning up the code, I decided I didn't like how I was passing more data to TimeBlocks than they needed so I restructured dayMap (renamed to crnSizeInfo) to easily pass only the necessary info.

2021-03-30 18:07 UTC, merged